### ISSUE TITLE
Batch Service GetRDPFile() fail to return the rdp

### ISSUE THREAD

**Issue by nagaraj-analytics** [Azure/azure-docs-sdk-dotnet#503]
please find the error message while we call this function

Microsoft.Azure.Batch.Common.BatchException: Operation returned an invalid status code 'Conflict' ---> Microsoft.Azure.Batch.Protocol.Models.BatchErrorException: Operation returned an invalid status code 'Conflict'
   at Microsoft.Azure.Batch.Protocol.ComputeNodeOperations.<GetRemoteDesktopWithHttpMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestWithCancellationAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestAsync>d__40.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.ProtocolLayer.<ProcessAndExecuteBatchRequest>d__84`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Batch.ProtocolLayer.<GetComputeNodeRDPFile>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.BatchExplorer.Models.ComputeNodeModel.<DownloadRDPAsync>d__38.MoveNext() in E:\Work\delete\azure-batch-samples-master\CSharp\BatchExplorer\Models\ComputeNodeModel.cs:line 318
Request Information
ClientRequestId:
RequestId:8c07a8b6-c8de-48e2-a83a-cd97e49618c6
HttpStatusCode:Conflict
StatusMessage:The specified operation is not valid on the node.

**Comment by CamSoper** [comment]
Hi there!  

This repo is for reference documentation.  Since this isn't a docs issue, please refer to the [Azure Batch feedback page](https://feedback.azure.com/forums/269742-batch) or submit a support request through the [Azure portal](https://portal.azure.com).

Thank you!  🙂
