### ISSUE TITLE
ExecuteNextAsync() is not threadsafe over multiple GremlinDocumentQuery instances

### ISSUE THREAD

**Issue by tjgalama** [Azure/azure-docs-sdk-dotnet#804]
I have an Azure Functions App (V2) that adds multiple vertices to a CosmosDB graph concurrently.
With an injected `DocumentClient` instance the (extension method) `CreateGremlinQuery(..)` is called returning a `GremlinDocumentQuery` instance. On this returned query 'ExecuteNextAsync()' async is called. 

When the method `ExecuteNextAsync()` is called simultaniously from multiple threads, soon or later an exception is thrown with the following stack: 

`   at System.Collections.Generic.Dictionary'2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary'2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.ReflectionCache.GetParametersCached(MethodBase method)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.BuildCompatibleArgumentProjection(MethodBase m, Expression[] exprArgs, List'1& projectedArgs)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.FindBestMethod(Expression instanceExpression, IEnumerable'1 methods, Type[] typeArgs, Expression[] args, MethodProjection& methodProjection)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.FindMethod(Expression instanceExpression, Type type, String methodName, Type[] typeArgs, Expression[] args, BindingFlags flags)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.<>c__DisplayClass6_0.<CreateTraversalScript>b__0(ParameterExpression p)
   at Microsoft.Azure.Graphs.GremlinGroovy.ParameterBinding.Create(GroovyVariable groovyVariable, ParameterExpression parameterExpression, Func'2 bindingExpressionFunc)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.CreateBinding(String variableName, String groovyClassName, ParameterExpression parameter, Func'2 bindingFunc)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.CreateTraversalScript(String gremlinScript)
   at Microsoft.Azure.Graphs.GraphCommand.<ExecuteTraversalAsync>b__42_0()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Graphs.GraphCommand.ExecuteTraversalAsync()
   at Microsoft.Azure.Graphs.GremlinDocumentQuery'1.InitializeGraphTraversalAync()
   at Microsoft.Azure.Graphs.GremlinDocumentQuery'1.ExecuteNextAsync[TResult](CancellationToken token)
   at FunctionAppOnCosmosDb.Function1.AddVertexChuck(CloudQueueMessage message, DocumentClient client, ILogger log, CancellationToken cancellationToken) in C:\Users\gat\Documents\Code\BagUpdateToGraph\FunctionAppOnCosmosDb\Function1.cs:line 69`

When I isolate the call to `ExecuteNextAsync()` within in a (static) thread lock enforcing this method to be called sequential no exception occurs. 
  
Although the type of the exception varies, it always occurred within `Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.ReflectionCache`. 
likely this has something to do with the non concurrent dictionary.

**Further info:**
I executed this Functions App locally on the CLI v2.6.0 (= ASP.NET Core 2.0).
my package references are:
- **Microsoft.Azure.Graphs  0.3.1-preview**
- Microsoft.Azure.WebJobs.Extensions.CosmosDB  3.0.1-rc1
- Microsoft.Azure.WebJobs.Extensions.Storage 3.0.0-rc1
- Microsoft.NET.Sdk.Functions 1.0.21

**Comment by jsquire** [comment]
Closing; the referenced package has been delisted and no longer exists.
